config/routes.rb
Rails.application.routes.draw do
  resources :artists, only: [:index, :new, :create, :show] do
    resources :albums
  end

  root "artists#index"
end

app/models/album.rb
class Album < ActiveRecord::Base
  belongs_to :artist

  validates :artist, presence: true
  validates :name, presence: true
end

app/models/artist.rb
class Artist < ActiveRecord::Base
  has_many :albums

  validates :name, presence: true
end

app/controllers/albums_controller.rb
class AlbumsController < ApplicationController
  def create
    artist = Artist.find(params[:artist_id])
    album = artist.albums.build(album_params)
    if album.save
      flash[:notice] = "New album created!"
    else
      flash[:error] = "Hey, you forgot something."
    end
    redirect_to artist
  end

  private

  def album_params
    params.require(:album).permit(:name)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/artists_controller.rb
class ArtistsController < ApplicationController
  def index
  end

  def new
    @artist = Artist.new
  end

  def create
    @artist = Artist.new(artist_params)
    if @artist.save
      flash[:notice] = "New artist created!"
      redirect_to artists_path
    else
      flash[:error] = "Fill out the form, silly."
      render :new
    end
  end

  def show
    @artist = Artist.find(params[:id])
    @album = Album.new
  end

  private

  def artist_params
    params.require(:artist).permit(:name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/artists/index.html.erb
<%= link_to "New Artist", new_artist_path %>

app/views/artists/new.html.erb
<h1>New Artist</h1>

<%= form_for @artist do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>

  <%= f.submit %>
<% end %>

app/views/artists/show.html.erb
<h1><%= @artist.name %></h1>


<h1>Add an album</h1>
<%= form_for [@artist, @album] do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>

  <%= f.submit %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "foundation-rails" %></title>

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "vendor/modernizr" %>
    <%= csrf_meta_tags %>
  </head>

  <body>
    <% flash.each do |type, message| %>
      <div class="flash flash-<%= type %>">
        <%= message %>
      </div>
    <% end %>

    <%= yield %>

  </body>
</html>